### ISSUE TITLE
Avoid invalid git remote names

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#166]
Remote names are generated based on app / aliases names. In some cases that leads to invalid remote names (eg `[prod] api`).

**Comment by hsablonniere** [comment]
It seems to come from and invalid range in the regex used to "slugify" the alias.

As we can see here:

https://github.com/CleverCloud/clever-tools/blob/d57871cf72f4fe50f1456d89a839ae53007a81ca/src/models/app_configuration.js#L45

The negative interval contains `A-z` which will match from uppercase `A` (ASCII-65) to  lower case `z` (ASCII-122) and this includes characters such as `[` or `]`.

**Comment by divarvel** [comment]
Indeed the regex is buggy.
I thought about it, and fixing the regex is not enough, since aliases can be provided manually.

A good solution would be:
 - extract the slugifying part into its own function
 - test it
 - call the slugify function in `Git.createRemote` (or slugify its argument)

**Comment by hsablonniere** [comment]
I agree about applying it directly in `Git.createRemote` but I would propose to use `_.kebabCase()` instead of doing it ourselves.

We already have `lodash` in our deps and this `kebabCase()` function has a good slugify behaviour. It would also prevent starting or ending with a dash which is not the case right now. I did a few tests and it translits characters like `é` to `e` and `ç` to `c` but it doesn't do full transliteration like `unidecode` with other characters like japanese, cyrillic...

I think we can combine both by applying `unidecode` then `_.kebabCase()`.

> extract the slugifying part into its own function

* Do we have a folder where we put this kind of utility functions?

**Comment by divarvel** [comment]
+1 on `_.kebabCase()`. I think you can put it in `models/application.js`
