### ISSUE TITLE
Restarting an application with a commit string shorter than expected tries to deploy commit #Infinity

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#167]
```
clever restart --commit 94e54206
Restarting <Project> on commit #Infinity
```

Using the full commit ID works as intended. I don't know if we can get the full commit ID from the short commit ID but we don't want to try to deploy the `#Infinity` commit anyway :)

**Comment by hsablonniere** [comment]
First discovery: it seems to come from cliparse when the commit id starts with a number...

**Comment by divarvel** [comment]
Oh, I think it's miniparse that tries to be clever (it does automatic type coertion…)

**Comment by hsablonniere** [comment]
https://github.com/substack/minimist/blob/master/index.js#L59

So here we can see that if `minimist` doesn't have an option listed in `opts.string` and if it's considered as a number with the magic homemade `isNumber`, it will be coerced with `Number()`.

The homemade `isNumber` matches commit ids like `01df24d2` 
 as numbers : https://github.com/substack/minimist/blob/master/index.js#L231

**Comment by hsablonniere** [comment]
So I guess that trying to "fix" the isNumber won't be a quick solution since we're not alone and it's very old, like 2014 old!

* https://github.com/substack/minimist/issues/36
* https://github.com/substack/minimist/issues/39
* https://github.com/substack/minimist/issues/87
* https://github.com/substack/minimist/issues/110
* https://github.com/substack/minimist/issues/112

If we pass `string: ['commit']` to minimist here it works.

https://github.com/divarvel/cliparse-node/blob/master/src/cli.js#L133-L137

So how do we pass this properly?

I propose that we use the parse and if it's set (manually or automatically) to string, we force minimist to consider it as a string.

**Comment by divarvel** [comment]
this solution looks good to me

**Comment by hsablonniere** [comment]
PR is ongoing on `cliparse` to fix this: https://github.com/divarvel/cliparse-node/pull/20

**Comment by hsablonniere** [comment]
Now that https://github.com/divarvel/cliparse-node/pull/20 is merged, the main symptom of this issue is fixed.

We now want to be able to accept short SHA1 with a local lookup in the local git repo and call the API with the full SHA1 if found.
