### ISSUE TITLE
Simplify login process

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-tools#224]
I don't know if that's something that has been rejected before but copy-pasting token & secret from the browser back to the terminal can be a bit cumbersome.

What about this login process:
- clever login starts a local HTTP server on port `localhost:XXXX`
- it then opens the browser
- the user login
- the oauth consumer callback URI is set to `http://localhost:XXXX`, the browser then redirect to the localhost callback uri
- the HTTP server receives the response with the tokens in the query string

Is it something that could be made? Does it make sense with OAUTH1?

**Comment by judu** [comment]
We were about to propose another process with @cnivolle but your idea is way better than ours!

Either way, we should definitely work on something. Because the copy/paste token+secret is annoying.

**Comment by waxzce** [comment]
I think it will make a security warning, on windows for example. But it can be possible to use a clilogin.clever-cloud.com app that will do the oauth dance for the CLI:
* the CLI declare a new oauth to the login-server and open a websocket to it
* the server respond with a URL for the dance open by the cli
* the oauth dance is performed with Clever Cloud and the login-server
* when the login server got the token, it send it with WS to the client
* it rocks

**Comment by hsablonniere** [comment]
We should do this without any local server.
I'd like to take the time to check how others do this.

I'm sure there's an "official" way to do this but if not, he's a suggestion:

* clever-tools generate a tmp random unique ID `123abc`
* clever-tools sends `123abc` to API
* clever-tools opens browser to login with `123abc` in the query string
* clever-tools polls API in the background
* user logs in browser as John Doe (with `123abc`)
* clever-tools polling receives tokens for John Doe since he successfully logged in as himself with `123abc`.

**Comment by hsablonniere** [comment]
This behavior is quiet similar to what TV apps do (like Plex).

**Comment by hsablonniere** [comment]
I wanted to display the same result as `clever profile` just after a login but I'm wondering if it's a good idea for CI environments.

**Comment by hsablonniere** [comment]
Not a problem since you will never do an interactive `clever login` in a CI env. You'll do it with the `--token` and `--secret`.

**Comment by hsablonniere** [comment]
Fixed by #260
