### ISSUE TITLE
Automate `.rpm` signature

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-tools#505]
We need to add the signature of `.rpm` in our build pipeline.

* https://github.com/CleverCloud/clever-tools/issues/454
* https://github.com/CleverCloud/clever-tools/pull/504
* https://github.com/CleverCloud/clever-tools/pull/467

**Comment by zepag** [comment]
In order to add signature, we need to import the gpg key in the container doing the build (in the context of the user doing the build), to create the appropriate setup (.rpmmacros file in the home folder of the signing user).
This being done, it will be possible to add the --sign argument to the rpm (fpm in this case) build and marvel at the result :).

**Comment by hsablonniere** [comment]
Fixed in #2.9.1 :tada:
